# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel Liu
email: idaniel.liu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  software developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://danielliu.xyz" # the base hostname & protocol for your site

timezone: America/Los_Angeles
sass:
  style: compressed

# Connections
# twitter_username: jekyllrb
github_username: danieliu
linkedin_username: idanielliu
# facebook_username: danieliu


# Build settings
markdown: kramdown
